-- DROP DELIVERY ATTEMPTS
DROP TABLE IF EXISTS delivery_attempts;

-- DROP DELIVERIES
DROP TABLE IF EXISTS deliveries;

-- DROP EVENTS
DROP TABLE IF EXISTS events;

-- DROP ENDPOINTS
DROP TABLE IF EXISTS endpoints;

-- DROP API KEYS
DROP TABLE IF EXISTS api_keys;

-- DROP APPLICATIONS
DROP TABLE IF EXISTS applications;

-- DROP EXTENSION
DROP EXTENSION IF EXISTS "pgcrypto";
